# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaceCalc_Bon_widget_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import io

import folium # pip install folium
import json
from folium.plugins import Draw
import folium.plugins as plugins


from PyQt5.QtWidgets import QApplication, QFileDialog, QVBoxLayout, QWidget
# from PyQt5.QtWebEngineWidgets import QWebEngineView

from PyQt5 import QtCore, QtGui, QtWidgets
# from MainWindow import Ui_MainWindow
# from  PyQt5.QtWidgets import  QFileDialog
from PyQt5.QtWebEngineWidgets import QWebEngineView


class Ui_m_MainWindow(QtWidgets.QMainWindow):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setupUi(self)
        # self.interfejs()
       
    
    def interfejs(self, vbox):
        # vbox = QVBoxLayout(self)
        # self.my_widget.a
        # vbox = gridLayout
        self.webEngineView = QWebEngineView()
        self.webEngineView.page().profile().downloadRequested.connect(
            self.handle_downloadRequested
        )
        self.loadPage()
        vbox.addWidget(self.webEngineView)
        self.setLayout(vbox)
        # self.my_widget.setLayout(vbox)
        # self.setGeometry(00, 0, 350, 250)
        self.resize(0, 0)
        self.setWindowTitle("mapy")
        # self.show()

    def loadPage(self):
        m = folium.Map(location=[28.695800, 77.244721],popup='Default popup Marker1',tooltip='Click here to see Popup')
        Draw(
            export=True,
            filename="my_data.geojson",
            position="topleft",
            draw_options={
                'polyline':False,
                'rectangle':False,
                'polygon':False,
                'circle':False,
                'marker': {'repeatMode': True},
                'circlemarker':False,
            },
            edit_options={
                "poly": {"allowIntersection": False},
                'edit':True},
        ).add_to(m)
        data = io.BytesIO()
        m.save(data, close_file=False)
        self.webEngineView.setHtml(data.getvalue().decode())

    def handle_downloadRequested(self, item):
        path, _ = QFileDialog.getSaveFileName(
            self, "Save File", item.suggestedFileName()
        )
        if path:
            item.setPath(path)
            item.accept()



    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(776, 563)
        MainWindow.setMinimumSize(QtCore.QSize(500, 400))
        MainWindow.setStyleSheet(u"font: 08pt \"MS Shell Dlg 2\";")
        
        
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_16.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setMaximumSize(QtCore.QSize(250, 500000))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_22.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_22.setText("")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_11.addWidget(self.lineEdit_22, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem, 8, 0, 1, 1)
        self.toolButton_13 = QtWidgets.QToolButton(self.frame_3)
        self.toolButton_13.setObjectName("toolButton_13")
        self.gridLayout_11.addWidget(self.toolButton_13, 2, 1, 1, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_23.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lineEdit_23.setText("")
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_15.addWidget(self.lineEdit_23, 0, 0, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_24.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lineEdit_24.setText("")
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_15.addWidget(self.lineEdit_24, 1, 0, 1, 1)
        self.dateTimeEdit_3 = QtWidgets.QDateTimeEdit(self.frame_3)
        self.dateTimeEdit_3.setMaximumSize(QtCore.QSize(400, 16777215))
        self.dateTimeEdit_3.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateTimeEdit_3.setObjectName("dateTimeEdit_3")
        self.gridLayout_15.addWidget(self.dateTimeEdit_3, 2, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_8.setEnabled(False)
        self.pushButton_8.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_15.addWidget(self.pushButton_8, 3, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.gridLayout_15.addLayout(self.verticalLayout_3, 4, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_12, 9, 0, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_25.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_25.setText("")
        self.lineEdit_25.setClearButtonEnabled(True)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_11.addWidget(self.lineEdit_25, 1, 0, 1, 1)
        self.toolButton_14 = QtWidgets.QToolButton(self.frame_3)
        self.toolButton_14.setObjectName("toolButton_14")
        self.gridLayout_11.addWidget(self.toolButton_14, 0, 1, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_26.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_26.setText("")
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout_11.addWidget(self.lineEdit_26, 4, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_5.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_5.setToolTip("")
        self.lineEdit_5.setWhatsThis("")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setClearButtonEnabled(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_11.addWidget(self.lineEdit_5, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem3, 10, 0, 1, 1)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_27.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_27.setText("")
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout_11.addWidget(self.lineEdit_27, 3, 0, 1, 1)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_28.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_28.setText("")
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout_11.addWidget(self.lineEdit_28, 5, 0, 1, 1)
        self.toolButton_15 = QtWidgets.QToolButton(self.frame_3)
        self.toolButton_15.setObjectName("toolButton_15")
        self.gridLayout_11.addWidget(self.toolButton_15, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem4, 9, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_9.setEnabled(False)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_9.setMouseTracking(False)
        self.pushButton_9.setToolTipDuration(5)
        self.pushButton_9.setAutoDefault(False)
        self.pushButton_9.setDefault(False)
        self.pushButton_9.setFlat(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_4.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_10.setEnabled(False)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_4.addWidget(self.pushButton_10)
        self.gridLayout_11.addLayout(self.horizontalLayout_4, 7, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_3.setChecked(False)
        self.checkBox_3.setAutoRepeat(False)
        self.checkBox_3.setTristate(False)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_11.addWidget(self.checkBox_3, 6, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame_3, 0, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_16.addWidget(self.line, 0, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 1, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setEnabled(False)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_17.setObjectName("gridLayout_17")
        # self.gridLayout_5.addWidget(self.widget_2, 0, 0, 1, 1)
        
        self.gridLayout_16.addLayout(self.gridLayout_5, 0, 2, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.progressBar_2 = QtWidgets.QProgressBar(self.widget)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.horizontalLayout_5.addWidget(self.progressBar_2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.gridLayout_16.addLayout(self.horizontalLayout_5, 1, 0, 1, 3)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 776, 21))
        self.menubar.setObjectName("menubar")
        self.menuOpen = QtWidgets.QMenu(self.menubar)
        self.menuOpen.setObjectName("menuOpen")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_New = QtWidgets.QAction(MainWindow)
        self.action_New.setObjectName("action_New")
        self.menuOpen.addAction(self.action_New)
        self.menubar.addAction(self.menuOpen.menuAction())


        # self.myMap = Mapy(self.widget_2)
        self.interfejs(self.gridLayout_5)
        
        
        self.retranslateUi(MainWindow)
        self.toolButton_14.clicked.connect(self.widget_2.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_5, self.toolButton_14)
        MainWindow.setTabOrder(self.toolButton_14, self.lineEdit_25)
        MainWindow.setTabOrder(self.lineEdit_25, self.toolButton_15)
        MainWindow.setTabOrder(self.toolButton_15, self.lineEdit_22)
        MainWindow.setTabOrder(self.lineEdit_22, self.toolButton_13)
        MainWindow.setTabOrder(self.toolButton_13, self.lineEdit_27)
        MainWindow.setTabOrder(self.lineEdit_27, self.lineEdit_26)
        MainWindow.setTabOrder(self.lineEdit_26, self.lineEdit_28)
        MainWindow.setTabOrder(self.lineEdit_28, self.checkBox_3)
        MainWindow.setTabOrder(self.checkBox_3, self.pushButton_9)
        MainWindow.setTabOrder(self.pushButton_9, self.pushButton_10)
        MainWindow.setTabOrder(self.pushButton_10, self.lineEdit_23)
        MainWindow.setTabOrder(self.lineEdit_23, self.lineEdit_24)
        MainWindow.setTabOrder(self.lineEdit_24, self.dateTimeEdit_3)
        
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_22.setPlaceholderText(_translate("MainWindow", "Chemin de sortie du fichier fgeo"))
        self.toolButton_13.setText(_translate("MainWindow", "..."))
        self.lineEdit_23.setPlaceholderText(_translate("MainWindow", "Longitude du point à calculer"))
        self.lineEdit_24.setPlaceholderText(_translate("MainWindow", "Latitude du point à calculer"))
        self.dateTimeEdit_3.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy HH:mm:ss"))
        self.pushButton_8.setText(_translate("MainWindow", "Calculer"))
        self.lineEdit_25.setPlaceholderText(_translate("MainWindow", "Chemin de sortie du fichier fpar"))
        self.toolButton_14.setText(_translate("MainWindow", "..."))
        self.lineEdit_26.setPlaceholderText(_translate("MainWindow", "Longitude origine (rad)"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Chemin du fichier BLQ.blq"))
        self.lineEdit_27.setPlaceholderText(_translate("MainWindow", "Distance de correlation (en Km)"))
        self.lineEdit_28.setPlaceholderText(_translate("MainWindow", "Latitude origine (rad)"))
        self.toolButton_15.setText(_translate("MainWindow", "..."))
        self.pushButton_9.setToolTip(_translate("MainWindow", "Supprimer des points du fichier BLQ"))
        self.pushButton_9.setWhatsThis(_translate("MainWindow", "Supprimer des points du fichier BLQ"))
        self.pushButton_9.setText(_translate("MainWindow", "Nettoyer"))
        self.pushButton_10.setText(_translate("MainWindow", "Calculer"))
        self.checkBox_3.setText(_translate("MainWindow", "Générer automatiquement des points"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.action_New.setText(_translate("MainWindow", "&New"))


# class Mapy(QWidget):
#     def __init__(self, parent=None):
#         super().__init__(parent)
#         # self.my_widget = my_widget
#         self.interfejs()

#     def interfejs(self):
#         vbox = QVBoxLayout(self)
#         # self.my_widget.a
#         # vbox = gridLayout
#         self.webEngineView = QWebEngineView()
#         self.webEngineView.page().profile().downloadRequested.connect(
#             self.handle_downloadRequested
#         )
#         self.loadPage()
#         vbox.addWidget(self.webEngineView)
#         self.setLayout(vbox)
#         # self.my_widget.setLayout(vbox)
#         # self.setGeometry(300, 300, 350, 250)
#         self.resize(776, 563)
#         self.setWindowTitle("mapy")
#         self.show()

#     def loadPage(self):
#         m = folium.Map(location=[51.7687323, 19.4569911], zoom_start=5)
#         Draw(
#             export=True,
#             filename="my_data.geojson",
#             position="topleft",
#             draw_options={
#                 "polyline": False,
#                 "rectangle": False,
#                 "circle": False,
#                 "circlemarker": False,
#             },
#             edit_options={"poly": {"allowIntersection": False}},
#         ).add_to(m)
#         data = io.BytesIO()
#         m.save(data, close_file=False)
#         self.webEngineView.setHtml(data.getvalue().decode())

#     def handle_downloadRequested(self, item):
#         path, _ = QFileDialog.getSaveFileName(
#             self, "Save File", item.suggestedFileName()
#         )
#         if path:
#             item.setPath(path)
#             item.accept()



if __name__ == '__main__':
    
    app = QtWidgets.QApplication(sys.argv)
    app.setStyleSheet('''
        QWidget {
            font-size: 35px;
        }
    ''')


    # widget = QtWidgets.QWidget() # or whatever your top-level class is
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_m_MainWindow()
    ui.setupUi(MainWindow)
    # widget.show()
    MainWindow.show()
    # ui.show()
    
    
    # myApp = Ui_Dialog()
    
    # myApp.show
    
    try:
        sys.exit(app.exec_())
    except SystemExit:
        print('Closing Window...')